# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: file_transfer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'file_transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66ile_transfer.proto\x12\x0c\x66iletransfer\"S\n\x08\x46ileInfo\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x10\n\x08\x66ilesize\x18\x02 \x01(\x03\x12\x0e\n\x06sha256\x18\x03 \x01(\t\x12\x13\n\x0bsender_name\x18\x04 \x01(\t\"T\n\tFileChunk\x12&\n\x04info\x18\x01 \x01(\x0b\x32\x16.filetransfer.FileInfoH\x00\x12\x14\n\nchunk_data\x18\x02 \x01(\x0cH\x00\x42\t\n\x07payload\"g\n\x0cUploadStatus\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nsaved_path\x18\x03 \x01(\t\x12\x16\n\x0e\x62ytes_received\x18\x04 \x01(\x03\x12\x0e\n\x06sha256\x18\x05 \x01(\t2Z\n\x13\x46ileTransferService\x12\x43\n\nUploadFile\x12\x17.filetransfer.FileChunk\x1a\x1a.filetransfer.UploadStatus(\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'file_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FILEINFO']._serialized_start=37
  _globals['_FILEINFO']._serialized_end=120
  _globals['_FILECHUNK']._serialized_start=122
  _globals['_FILECHUNK']._serialized_end=206
  _globals['_UPLOADSTATUS']._serialized_start=208
  _globals['_UPLOADSTATUS']._serialized_end=311
  _globals['_FILETRANSFERSERVICE']._serialized_start=313
  _globals['_FILETRANSFERSERVICE']._serialized_end=403
# @@protoc_insertion_point(module_scope)
